const tabsData = [
    {
      id: 1,
      tabTitle: "Europe",
      selectBtnLink1: "#",
      selectBtnLink2: "#",
      selectBtnLink3: "#",
      selectBtnLink4: "#",
      selectBtnLink5: "#",
      selectBtnLink6: "#",
      list1: `250 GB Object Storage in Europe`,
      list2: `500 GB Object Storage in Europe`,
      list3: `1 TB Object Storage in Europe`,
      list4: `2 TB Object Storage in Europe`,
      list5: `5 TB Object Storage in Europe`,
      list6: `10 TB Object Storage in Europe`,
      price1: `2.99`,
      price2: `5.98`,
      price3: `11.96`,
      price4: `23.92`,
      price5: `59.80`,
      price6: `119.60`,
    },
    {
      id: 2,
      tabTitle: "United States",
      selectBtnLink1: "#",
      selectBtnLink2: "#",
      selectBtnLink3: "#",
      selectBtnLink4: "#",
      selectBtnLink5: "#",
      selectBtnLink6: "#",
      list1: `250 GB Object Storage in United States`,
      list2: `500 GB Object Storage in United States`,
      list3: `1 TB Object Storage in United States`,
      list4: `2 TB Object Storage in United States`,
      list5: `5 TB Object Storage in United States`,
      list6: `10 TB Object Storage in United States`,
      price1: `2.99`,
      price2: `5.98`,
      price3: `11.96`,
      price4: `23.92`,
      price5: `59.80`,
      price6: `119.60`,
    },
    {
      id: 3,
      tabTitle: "Asia",
      selectBtnLink1: "#",
      selectBtnLink2: "#",
      selectBtnLink3: "#",
      selectBtnLink4: "#",
      selectBtnLink5: "#",
      selectBtnLink6: "#",
      list1: `250 GB Object Storage in Singapore`,
      list2: `500 GB Object Storage in Singapore`,
      list3: `1 TB Object Storage in Singapore`,
      list4: `2 TB Object Storage in Singapore`,
      list5: `5 TB Object Storage in Singapore`,
      list6: `10 TB Object Storage in Singapore`,
      price1: `3.39`,
      price2: `6.78`,
      price3: `13.56`,
      price4: `27.12`,
      price5: `67.80`,
      price6: `135.60`,
    },
  ];

  export default tabsData;