const LinuxData = {

  linuxCard: [
    {
      id: 0,
      cardlinuxTitle: "RockeyBoost",
      Linkss: `/beta-madpopo-react-app/LinuxWebHosting`,
      cardlinuxSubTitle: "Optimal solution for Beginners",
      cardlinuxOgPrice: `$32`,
      cardlinuxOffer: "offer - 30%",
      cardlinuxCapacity: "10GB",
      cardlinuxSSHAccess: "Unlimited",
      cardlinuxOPt1: "Free Domain 1st Year*",
      cardlinuxOPT2: `1`,
      cardlinuxOPT3: `10`,
      cardlinuxOPT4: `20`,
      cardlinuxOPT5: `2`,
      cardlinuxOPT6: `Weekly Backup`,
      priceYearlyInINR: 120,
      priceTwoYearlyInINR: 140,
      priceThreeYearlyInINR: 160,
      priceYearlyInUSD: 13,
      priceTwoYearlyInUSD: 14,
      priceThreeYearlyInUSD: 17,
      priceYearlyInEUR: 12,
      priceTwoYearlyInEUR: 13,
      priceThreeYearlyInEUR: 16,
    },
    {
      id: 1,
      cardlinuxTitle: "RockyPro",
      Linkss: `/beta-madpopo-react-app/LinuxWebHosting`,
      cardlinuxSubTitle: "Ideal for personal websites",
      cardlinuxOgPrice: `$33`,
      cardlinuxOffer: "offer - 30%",
      cardlinuxCapacity: "20GB",
      cardlinuxSSHAccess: "Unlimited",
      cardlinuxOPt1: "Free Domain 1st Year*",
      cardlinuxOPT2: `5`,
      cardlinuxOPT3: `20`,
      cardlinuxOPT4: `50`,
      cardlinuxOPT5: `10`,
      cardlinuxOPT6: `Weekly Backup`,
      priceYearlyInINR: 220,
      priceTwoYearlyInINR: 240,
      priceThreeYearlyInINR: 260,
      priceYearlyInUSD: 23,
      priceTwoYearlyInUSD: 24,
      priceThreeYearlyInUSD: 27,
      priceYearlyInEUR: 22,
      priceTwoYearlyInEUR: 23,
      priceThreeYearlyInEUR: 26,
    },
    {
      id: 2,
      cardlinuxTitle: "RockyBusiness",
      Linkss: `/beta-madpopo-react-app/LinuxWebHosting`,
      cardlinuxSubTitle: "Suitable for small business.",
      cardlinuxOgPrice: `$34`,
      cardlinuxOffer: "offer - 30%",
      cardlinuxCapacity: "30GB",
      cardlinuxSSHAccess: "Unlimited",
      cardlinuxOPt1: "Free Domain 1st Year*",
      cardlinuxOPT2: `10`,
      cardlinuxOPT3: `30`,
      cardlinuxOPT4: `100`,
      cardlinuxOPT5: `20`,
      cardlinuxOPT6: `Daily Backup`,
      priceYearlyInINR: 320,
      priceTwoYearlyInINR: 340,
      priceThreeYearlyInINR: 360,
      priceYearlyInUSD: 33,
      priceTwoYearlyInUSD: 34,
      priceThreeYearlyInUSD: 37,
      priceYearlyInEUR: 32,
      priceTwoYearlyInEUR: 33,
      priceThreeYearlyInEUR: 36,
    },
  ],
};
export default LinuxData;
