const VpsData=[
    {
        id: 1,
        cardVpsTitle: "PopoStarter",
        cardVpsSubTitle: "Optimal solution for Beginners",
        cardVpsImg:'../../src/image/PopoPro.png',
        cardVpsAltName:`PopoStarter`,
        cardVpsOgPrice: `$32`,
        cardVpsOffer: "offer - 30%",
        cardVpsCapacity: "10GB",
        cardVpsSSHAccess: "Unlimited",
        cardVpsOPt1: "Free Domain 1st Year*",
        cardVpsOPT2:`1`,
        cardVpsOPT3:`10`,
        cardVpsOPT4:`20`,
        cardVpsOPT5:`2`,
        cardVpsOPT6:`Weekly Backup`,
        
      },
      {
        id: 2,
        cardVpsTitle: "PopoPro ",
        cardVpsSubTitle: "Ideal for personal websites",
        cardVpsImg:`../../src/image/PopoPro.png`,
        cardVpsAltName:`PopoPro `,
        cardVpsOgPrice: `$33`,
        cardVpsOffer: "offer - 30%",
        cardVpsCapacity: "20GB",
        cardVpsSSHAccess: "Unlimited",
        cardVpsOPt1: "Free Domain 1st Year*",
        cardVpsOPT2:`5`,
        cardVpsOPT3:`20`,
        cardVpsOPT4:`50`,
        cardVpsOPT5:`10`,
        cardVpsOPT6:`Weekly Backup`,
        
      },
      {
        id: 3,
        cardVpsTitle: "PopoGrow",
        cardVpsSubTitle: "Suitable for small business.",
        cardVpsImg:`../../src/image/PopoGrow.png`,
        cardVpsAltName:`PopoGrow`,
        cardVpsOgPrice: `$34`,
        cardVpsOffer: "offer - 30%",
        cardVpsCapacity: "30GB",
        cardVpsSSHAccess: "Unlimited",
        cardVpsOPt1: "Free Domain 1st Year*",
        cardVpsOPT2:`10`,
        cardVpsOPT3:`30`,
        cardVpsOPT4:`100`,
        cardVpsOPT5:`20`,
        cardVpsOPT6:`Daily Backup`,
        
      },
]
export default VpsData;