const VpsData = [
  {
    id: 1,
    cardVpsTitle: "PopoStarter",
    cardVpsSubTitle: "Optimal solution for Beginners",
    cardAnchorLink: `/beta-madpopo-react-app/VirtualDedicatedServer`,
    cardVpsImg: "https://be.madpopo.com/static/media/PopoStarter.png",
    cardVpsAltName: `PopoStarter`,
    cardVpsOgPrice: `$23`,
    cardVpsWebSpace: "4",
    cardVpsCapacity: "8",
    cardVpsCapacity2: "50 GB",
    cardVpsCapacity3: "200 GB",
    cardVpsSnap: "1",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `1`,
    cardVpsOPT3: `10`,
    cardVpsOPT4: `20`,
    cardVpsOPT5: `2`,
    cardVpsOPT6: `Weekly Backup`,
    priceYearlyInINR: 120,
    priceTwoYearlyInINR: 140,
    priceThreeYearlyInINR: 160,
    priceYearlyInUSD: 13,
    priceTwoYearlyInUSD: 14,
    priceThreeYearlyInUSD: 17,
    priceYearlyInEUR: 12,
    priceTwoYearlyInEUR: 13,
    priceThreeYearlyInEUR: 16,
  },
  {
    id: 2,
    cardVpsTitle: "PopoPro ",
    cardVpsSubTitle: "Ideal for personal websites",
    cardAnchorLink: `/beta-madpopo-react-app/VirtualDedicatedServer`,
    cardVpsImg: `https://be.madpopo.com/static/media/PopoPro.png`,
    cardVpsAltName: `PopoPro `,
    cardVpsOgPrice: `$24`,
    cardVpsWebSpace: "6",
    cardVpsCapacity: "16",
    cardVpsCapacity2: "100 GB",
    cardVpsCapacity3: "400 GB",
    cardVpsSnap: "2",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `5`,
    cardVpsOPT3: `20`,
    cardVpsOPT4: `50`,
    cardVpsOPT5: `10`,
    cardVpsOPT6: `Weekly Backup`,
    priceYearlyInINR: 220,
    priceTwoYearlyInINR: 240,
    priceThreeYearlyInINR: 260,
    priceYearlyInUSD: 23,
    priceTwoYearlyInUSD: 24,
    priceThreeYearlyInUSD: 27,
    priceYearlyInEUR: 22,
    priceTwoYearlyInEUR: 23,
    priceThreeYearlyInEUR: 26,
  },
  {
    id: 3,
    cardVpsTitle: "PopoGrow",
    cardVpsSubTitle: "Suitable for small business.",
    cardAnchorLink: `/beta-madpopo-react-app/VirtualDedicatedServer`,
    cardVpsImg: `https://be.madpopo.com/static/media/PopoGrow.png`,
    cardVpsAltName: `PopoGrow`,
    cardVpsOgPrice: `$25`,
    cardVpsWebSpace: "10",
    cardVpsCapacity: "60",
    cardVpsCapacity2: "400 GB",
    cardVpsCapacity3: "1.6 TB",
    cardVpsSnap: "4",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `10`,
    cardVpsOPT3: `30`,
    cardVpsOPT4: `100`,
    cardVpsOPT5: `20`,
    cardVpsOPT6: `Daily Backup`,
    priceYearlyInINR: 320,
    priceTwoYearlyInINR: 340,
    priceThreeYearlyInINR: 360,
    priceYearlyInUSD: 33,
    priceTwoYearlyInUSD: 34,
    priceThreeYearlyInUSD: 37,
    priceYearlyInEUR: 32,
    priceTwoYearlyInEUR: 33,
    priceThreeYearlyInEUR: 36,
  },
];
export default VpsData;
