const VssData = [
    {
      id: 1,
      cardVpsTitle: "VSS 1",
      cardVpsSubTitle: "Optimal solution for Beginners", 
      cardAnchorLink: `/virtual-server`,
      cardVpsImg: "https://madpopo.com/static/media/PopoStarter.png",
      cardVpsAltName: `PopoStarter`,
      cardVpsOgPrice: `$23`,
      cardVpsWebSpace: "4",
      cardVpsCapacity: "8",
      cardVpsCapacity2: "50 GB",
      cardVpsCapacity3: "200 GB",
      cardVpsSnap: "1",
      cardVpsOPt1: "Free Domain 1st Year*",
      cardVpsOPT2: `1`,
      cardVpsOPT3: `10`,
      cardVpsOPT4: `20`,
      cardVpsOPT5: `2`,
      cardVpsOPT6: `Weekly Backup`,
      priceYearlyInINR: 1699,
      priceTwoYearlyInINR: 1599,
      priceThreeYearlyInINR: 1499,
      priceYearlyInUSD: 21.99,
      priceTwoYearlyInUSD: 19.99,
      priceThreeYearlyInUSD: 8.99,
      priceYearlyInEUR: 21,
      priceTwoYearlyInEUR: 19,
      priceThreeYearlyInEUR: 18,
    },
    {
      id: 2,
      cardVpsTitle: "VSS 2 ",
      cardVpsSubTitle: "Ideal for personal websites",
      cardAnchorLink: `/virtual-server`,
      cardVpsImg: `https://madpopo.com/static/media/PopoPro.png`,
      cardVpsAltName: `PopoPro `,
      cardVpsOgPrice: `$24`,
      cardVpsWebSpace: "6",
      cardVpsCapacity: "16",
      cardVpsCapacity2: "100 GB",
      cardVpsCapacity3: "400 GB",
      cardVpsSnap: "2",
      cardVpsOPt1: "Free Domain 1st Year*",
      cardVpsOPT2: `5`,
      cardVpsOPT3: `20`,
      cardVpsOPT4: `50`,
      cardVpsOPT5: `10`,
      cardVpsOPT6: `Weekly Backup`,
      priceYearlyInINR: 2399,
      priceTwoYearlyInINR: 2199,
      priceThreeYearlyInINR: 1999,
      priceYearlyInUSD: 26.99,
      priceTwoYearlyInUSD: 25.99,
      priceThreeYearlyInUSD: 24.99,
      priceYearlyInEUR: 26,
      priceTwoYearlyInEUR: 25,
      priceThreeYearlyInEUR: 24,
    },
    {
      id: 3,
      cardVpsTitle: "VSS 3",
      cardVpsSubTitle: "Suitable for small business.",
      cardAnchorLink: `/virtual-server`,
      cardVpsImg: `https://madpopo.com/static/media/PopoGrow.png`,
      cardVpsAltName: `PopoGrow`,
      cardVpsOgPrice: `$25`,
      cardVpsWebSpace: "10",
      cardVpsCapacity: "60",
      cardVpsCapacity2: "400 GB",
      cardVpsCapacity3: "1.6 TB",
      cardVpsSnap: "4",
      cardVpsOPt1: "Free Domain 1st Year*",
      cardVpsOPT2: `10`,
      cardVpsOPT3: `30`,
      cardVpsOPT4: `100`,
      cardVpsOPT5: `20`,
      cardVpsOPT6: `Daily Backup`,
      priceYearlyInINR: 4299,
      priceTwoYearlyInINR: 4199,
      priceThreeYearlyInINR: 3999,
      priceYearlyInUSD: 52.99,
      priceTwoYearlyInUSD: 51.99,
      priceThreeYearlyInUSD: 49.99,
      priceYearlyInEUR: 52,
      priceTwoYearlyInEUR: 51,
      priceThreeYearlyInEUR: 49,
    },
  ];
  export default VssData;
  