const WindowsHostingDatas = [

      {
        id: 1,
        winHostTitle: "WinStarter",
        winHostSubTitle: "Optimal solution for Beginners",
        winHostOgPrice: `$32.99`,
        winHostDiscPrice: `$30.99`,
        winHostOffer: "offer - 30%",
        winHostCapacity: "5GB",
        winHostSSHAccess: "Unlimited",
        winHostDDOS: "1",
        winHOPt1: "10",
        winHOPt2:`20`,
        winHOPt3:`2`,
        winHOPt4:`20`,
        winHOPt5:`2`,
        winHOPt6:`Weekly Backup`,
      },
      {
        id: 2,
        winHostTitle: "WinPro",
        winHostSubTitle: "Ideal for personal websites",
        winHostOgPrice: `$33.99`,
        winHostDiscPrice: `$31.99`,
        winHostOffer: "offer - 40%",
        winHostCapacity: "10GB",
        winHostSSHAccess: "Unlimited",
        winHostDDOS: "5",
        winHOPt1: "20",
        winHOPt2:`50`,
        winHOPt3:`10`, 
        winHOPt4:`20`,
        winHOPt5:`2`,
        winHOPt6:`Weekly Backup`,
      },
      {
        id: 3,
        winHostTitle: "WinGrow",
        winHostSubTitle: "Suitable for small business",
        winHostOgPrice: `$34.99`,
        winHostDiscPrice: `$32.99`,
        winHostOffer: "offer - 30%",
        winHostCapacity: "20GB",
        winHostSSHAccess: "Unlimited",
        winHNode:`10`,
        winHostDDOS: "10",
        winHOPt1: "30",
        winHOPt2:`100`,
        winHOPt3:`20`,
        winHOPt4:`20`,
        winHOPt5:`2`,
        winHOPt6:`Daily Backup`,
      },
    
    ];
  export default WindowsHostingDatas;
  