const WindowsHostingDatas = [
  {
    id: 1,
    winHostTitle: "WinStarter",
    winHostSubTitle: "Optimal solution for Beginners",
    winHostAnchor: "/beta-madpopo-react-app/WindowsWebHosting",
    winHostOgPrice: `$32.99`,
    winHostDiscPrice: `$30.99`,
    winHostOffer: "offer - 30%",
    winHostCapacity: "5GB",
    winHostSSHAccess: "Unlimited",
    winHostDDOS: "1",
    winHOPt1: "10",
    winHOPt2: `20`,
    winHOPt3: `2`,
    winHOPt4: `20`,
    winHOPt5: `2`,
    winHOPt6: `Weekly Backup`,
    priceYearlyInINR: 120,
    priceTwoYearlyInINR: 140,
    priceThreeYearlyInINR: 160,
    priceYearlyInUSD: 13,
    priceTwoYearlyInUSD: 14,
    priceThreeYearlyInUSD: 17,
    priceYearlyInEUR: 12,
    priceTwoYearlyInEUR: 13,
    priceThreeYearlyInEUR: 16,
  },
  {
    id: 2,
    winHostTitle: "WinPro",
    winHostSubTitle: "Ideal for personal websites",
    winHostAnchor: "/beta-madpopo-react-app/WindowsWebHosting",
    winHostOgPrice: `$33.99`,
    winHostDiscPrice: `$31.99`,
    winHostOffer: "offer - 40%",
    winHostCapacity: "10GB",
    winHostSSHAccess: "Unlimited",
    winHostDDOS: "5",
    winHOPt1: "20",
    winHOPt2: `50`,
    winHOPt3: `10`,
    winHOPt4: `20`,
    winHOPt5: `2`,
    winHOPt6: `Weekly Backup`,
    priceYearlyInINR: 220,
    priceTwoYearlyInINR: 240,
    priceThreeYearlyInINR: 260,
    priceYearlyInUSD: 23,
    priceTwoYearlyInUSD: 24,
    priceThreeYearlyInUSD: 27,
    priceYearlyInEUR: 22,
    priceTwoYearlyInEUR: 23,
    priceThreeYearlyInEUR: 26,
  },
  {
    id: 3,
    winHostTitle: "WinGrow",
    winHostSubTitle: "Suitable for small business",
    winHostAnchor: "/beta-madpopo-react-app/WindowsWebHosting",
    winHostOgPrice: `$34.99`,
    winHostDiscPrice: `$32.99`,
    winHostOffer: "offer - 30%",
    winHostCapacity: "20GB",
    winHostSSHAccess: "Unlimited",
    winHNode: `10`,
    winHostDDOS: "10",
    winHOPt1: "30",
    winHOPt2: `100`,
    winHOPt3: `20`,
    winHOPt4: `20`,
    winHOPt5: `2`,
    winHOPt6: `Daily Backup`,
    priceYearlyInINR: 320,
    priceTwoYearlyInINR: 340,
    priceThreeYearlyInINR: 360,
    priceYearlyInUSD: 33,
    priceTwoYearlyInUSD: 34,
    priceThreeYearlyInUSD: 37,
    priceYearlyInEUR: 32,
    priceTwoYearlyInEUR: 33,
    priceThreeYearlyInEUR: 36,
  },
];
export default WindowsHostingDatas;
