export { default as logo1 } from "../../src/image/header/madpopo-dark-logo.svg";
export { default as logo2 } from "../../src/image/header/madpopo-white-logo.svg";
export { default as bannerBg1 } from "../../src/image/header/sunset-version/moon.png";
export { default as bannerBg2 } from "../../src/image/header/helf-circle-01.png";
export { default as bannerBg3 } from "../../src/image/header/helf-circle-02.png";
export { default as bannerBg4 } from "../../src/image/header/helf-circle-03.png";

export { default as conImg1 } from "../../src/image/pages/contact/madpopo_chat.png";
export { default as conImg2 } from "../../src/image/pages/contact/madpopo_email.png";

export { default as downArrowBlack } from "../../src/image/header/down-arrow-black.png";
export { default as downArrowWhite } from "../../src/image/header/down-arrow-white.png";

export { default as bannerBg5 } from "../../src/image/payment/icon-visa.png";
export { default as bannerBg6 } from "../../src/image/payment/icon-maestro.png";
export { default as bannerBg7 } from "../../src/image/payment/icon-bitcoin.png";

export { default as woldMap } from "../../src/image/world-map/wolrd-map.webp";
export { default as fooLogo } from "../../src/image/header/madpopo-white-logo.svg";
export { default as bgleftMid } from "../../src/image/left-mid-elm.png";
export { default as bgRightMid } from "../../src/image/right-elm.png"; 
export { default as avtarImg } from "../../src/image/avtar.webp";
export { default as pcImage } from "../../src/image/header-pc.png";
export { default as pcImage2 } from "../../src/image/header-pc2.png";
export { default as pcImage3 } from "../../src/image/computer_table.png";
export { default as faceImage } from "../../src/image/face_1.png";
export { default as yogaImg } from "../../src/image/popo-yoga2.webp";
export { default as footerPose1 } from "../../src/image/footer_pose-1.png";

export { default as migration } from "../../src/image/migrationmeeting.webp";
export { default as wpHostRightImg } from "../../src/image/extremely-fast-performance.webp";
export { default as wpHostLefttImg } from "../../src/image/24-7-support.webp";
export { default as wpFeatureImg1 } from "../../src/image/wordpress/Optimized-Technology-new.webp";
export { default as wpFeatureImg2 } from "../../src/image/wordpress/WordPress-Staging-Tool-new.webp";
export { default as wpFeatureImg3 } from "../../src/image/wordpress/Automatic-Updates-new.webp";
export { default as wpFeatureImg4 } from "../../src/image/wordpress/1-Click WordPress-Installer-new.webp";
export { default as wpFeatureImg5 } from "../../src/image/wordpress/Automated-Backups-new.webp";
export { default as wpFeatureImg6 } from "../../src/image/wordpress/WordPress-Pro-Features-new.webp";
export { default as wpFeatureImg7 } from "../../src/image/wordpress/fast-solid-state-storage.png";
export { default as wpFeatureImg8 } from "../../src/image/wordpress/ssls.png";
export { default as wpFeatureImg9 } from "../../src/image/wordpress/server-level-caching.png";
export { default as wpFeatureImg10 } from "../../src/image/wordpress/100-Uptime.png";
export { default as wpFeatureImg11 } from "../../src/image/wordpress/scalable-hosting.png";
export { default as wpFeatureImg12 } from "../../src/image/wordpress/malware-scan-removal.png";
export { default as wpFeatureImg13 } from "../../src/image/wordpress/free-sssl-certificate.png";
export { default as wpFeatureImg14 } from "../../src/image/wordpress/highly-secure-reliable.png";

export { default as navicon1 } from "../../src/image/header/navbaricon/wordpressicon.png";
export { default as navicon2 } from "../../src/image/header/navbaricon/woocomicon.png";
export { default as navicon3 } from "../../src/image/header/navbaricon/linuxicon.png";
export { default as navicon4 } from "../../src/image/header/navbaricon/windowsicon.png";
export { default as navicon5 } from "../../src/image/header/navbaricon/virtual-dedicated-server.png";
export { default as navicon6 } from "../../src/image/header/navbaricon/dedicated-server.png";
export { default as navicon7 } from "../../src/image/header/navbaricon/Emailicon.png";
export { default as navicon8 } from "../../src/image/header/navbaricon/Resellericon.png";

export { default as rigions } from "../../src/image/pages/globalInfra/8-regions.png";
export { default as dc } from "../../src/image/pages/globalInfra/14-data-center.png";
export { default as nc } from "../../src/image/pages/globalInfra/35-nc.png";
export { default as DomainImg3 } from "../../src/image/FREE-E-mail-Forwarding.webp";
export { default as WinIMg2 } from "../../src/image/plesk-control.webp";
export { default as wp_logo } from "../../src/image/wordpress_innerlogo.png";
export { default as tableImg } from "../../src/image/24_shadow.png";
export { default as webSpeedImg } from "../../src/image/popo-site-load-test_1-80.webp";
export { default as domainimg1 } from "../../src/image/domain/tech-domain.png";
export { default as domainimg2 } from "../../src/image/domain/biz-domain.png";
export { default as domainimg3 } from "../../src/image/domain/com-domain.png";
export { default as domainimg4 } from "../../src/image/domain/in-domain.png";
export { default as domainimg5 } from "../../src/image/domain/info-domain.png";
export { default as domainimg6 } from "../../src/image/domain/name.webp";
export { default as domainimg7 } from "../../src/image/domain/net-domain.png";
export { default as domainimg8 } from "../../src/image/domain/online.webp";
export { default as domainimg9 } from "../../src/image/domain/org-domain.png";
export { default as domainimg10 } from "../../src/image/domain/shop.webp";
export { default as securitymadpopo } from "../../src/image/pages/globalInfra/security-madpopo.jpg";
export { default as conditionpower } from "../../src/image/pages/globalInfra/condition-power.jpg";
export { default as precisionenvironment } from "../../src/image/pages/globalInfra/madpopo-precision-environment.jpg";
export { default as networkmadpopo } from "../../src/image/pages/globalInfra/network-madpopo.jpg";
export { default as networkswitchequipment } from "../../src/image/pages/globalInfra/network-switch-equipment.jpg";
export { default as physicalsecurity } from "../../src/image/pages/globalInfra/physical-security.jpg";
export { default as migrationWp } from "../../src/image/wordpress/wp-3d-logo.webp";
export { default as bus_rightImg } from "../../src/image/pages/businessemail/besrightimg.webp";
export { default as linusRightImg } from "../../src/image/pages/linuxwebhosting/linux-hosting.webp";
export { default as windowsImg } from "../../src/image/pages/windows/windows-object.webp";
export { default as vdsImg } from "../../src/image/pages/virtualserver/cloud-server.webp";
export { default as dsImg } from "../../src/image/pages/dedicatedserver/dedicatedserverimg.webp";
export { default as woocommimg } from "../../src/image/pages/woocomeerce/woocomimg.webp";
export { default as vdsImgOne } from "../../src/image/secure-server-one.png";
export { default as vdsImgTwo } from "../../src/image/Quickly-Provisioning.webp";
export { default as vdsImgThree } from "../../src/image/High-availability.webp";
export { default as vdsImgFour } from "../../src/image/Global-Availability.webp";
export { default as vdsImgFive } from "../../src/image/Best-Price-at-Best-Performance.webp";
export { default as vdsImgSix } from "../../src/image/Support-Round-The-Clock.webp";
export { default as vdsImgSeven } from "../../src/image/Storage-I-O-load-balancing.webp";
export { default as INRFlag } from "../../src/image/inr.png";
export { default as EURFlag } from "../../src/image/euro.png";
export { default as USDFlag } from "../../src/image/usa.png";
export { default as wcasia } from "../../src/image/Mad_Popo_Form_WCAsia.webp";
export { default as palnsIcon } from "../../src/image/pointer.png";
export { default as visa } from "../../src/image/footer/visa.webp";
export { default as amex } from "../../src/image/footer/amex.webp";
export { default as discover } from "../../src/image/footer/discover.webp";
export { default as jcb } from "../../src/image/footer/jcb.webp";
export { default as maestro } from "../../src/image/footer/maestro.webp";
export { default as mastercard } from "../../src/image/footer/mastercard.webp";

export { default as homeEl1 } from "../../src/image/header/hero-light-1.png";
export { default as homeEl2 } from "../../src/image/header/service-3.png";
export { default as homeEl3 } from "../../src/image/header/service-1.png";
export { default as homeEl4 } from "../../src/image/header/hero-light-2.png";

export { default as reason1 } from "../../src/image/pages/career/icon_stability.svg";
export { default as reason2 } from "../../src/image/pages/career/icon_diversity.svg";
export { default as reason3 } from "../../src/image/pages/career/icon_training.svg";
export { default as reason4 } from "../../src/image/pages/career/icon_mobile-office.svg";
export { default as reason5 } from "../../src/image/pages/career/icon_refreshments.svg";
export { default as reason6 } from "../../src/image/pages/career/icon_growth.svg";

