const products = {
  wordpressData: [
    {
      id: 0,
      name: "POPO L", 
      priceYearlyInINR: 120,
      priceTwoYearlyInINR: 140,
      priceThreeYearlyInINR: 160,
      priceYearlyInUSD: 13,
      priceTwoYearlyInUSD: 14,
      priceThreeYearlyInUSD: 17,
      priceYearlyInEUR: 12,
      priceTwoYearlyInEUR: 13,
      priceThreeYearlyInEUR: 16,
    },
    {
      id: 1,
      name: "POPO XL",
      priceYearlyInINR: 220,
      priceTwoYearlyInINR: 240,
      priceThreeYearlyInINR: 260,
      priceYearlyInUSD: 23,
      priceTwoYearlyInUSD: 24,
      priceThreeYearlyInUSD: 27,
      priceYearlyInEUR: 22,
      priceTwoYearlyInEUR: 23,
      priceThreeYearlyInEUR: 26,
    },
    {
      id: 2,
      name: "POPO XXL",
      priceYearlyInINR: 320,
      priceTwoYearlyInINR: 340,
      priceThreeYearlyInINR: 360,
      priceYearlyInUSD: 33,
      priceTwoYearlyInUSD: 34,
      priceThreeYearlyInUSD: 37,
      priceYearlyInEUR: 32,
      priceTwoYearlyInEUR: 33,
      priceThreeYearlyInEUR: 36,
    },
   
  ],
  linuxData: [
    {
      id: 0,
      name: "RockeyBoost",
      priceYearlyInINR: 120,
      priceTwoYearlyInINR: 140,
      priceThreeYearlyInINR: 160,
      priceYearlyInUSD: 13,
      priceTwoYearlyInUSD: 14,
      priceThreeYearlyInUSD: 17,
      priceYearlyInEUR: 12,
      priceTwoYearlyInEUR: 13,
      priceThreeYearlyInEUR: 16,
    },
    {
      id: 1,
      name: "RockyPro",
      priceYearlyInINR: 220,
      priceTwoYearlyInINR: 240,
      priceThreeYearlyInINR: 260,
      priceYearlyInUSD: 23,
      priceTwoYearlyInUSD: 24,
      priceThreeYearlyInUSD: 27,
      priceYearlyInEUR: 22,
      priceTwoYearlyInEUR: 23,
      priceThreeYearlyInEUR: 26,
    },
    {
      id: 2,
      name: "RockyBusiness",
      priceYearlyInINR: 320,
      priceTwoYearlyInINR: 340,
      priceThreeYearlyInINR: 360,
      priceYearlyInUSD: 33,
      priceTwoYearlyInUSD: 34,
      priceThreeYearlyInUSD: 37,
      priceYearlyInEUR: 32,
      priceTwoYearlyInEUR: 33,
      priceThreeYearlyInEUR: 36,
    },
   
  ],
};

export default products;
