const products = {
  wordpressData: [
    {
      id: 0,
      name: "POPO L", 
      priceYearlyInINR: 339,
      priceTwoYearlyInINR: 319,
      priceThreeYearlyInINR: 299,
      priceYearlyInUSD: 4.5,
      priceTwoYearlyInUSD: 4.3,
      priceThreeYearlyInUSD: 3.9,
      priceYearlyInEUR: 4.2,
      priceTwoYearlyInEUR: 4,
      priceThreeYearlyInEUR: 3,
      // Save the price data
      priceYearlySaveInINR:  33999,
      priceTwoYearlySaveInINR:  33999,
      priceThreeYearlySaveInINR:  33999,
      priceYearlySaveInUSD:399,
      priceTwoYearlySaveInUSD: 399,
      priceThreeYearlySaveInUSD: 399,
      priceYearlySaveInEUR: 369,
      priceTwoYearlySaveInEUR: 369,
      priceThreeYearlySaveInEUR: 369,
      
    },
    {
      id: 1,
      name: "POPO XL",
      priceYearlyInINR: 479,
      priceTwoYearlyInINR: 469,
      priceThreeYearlyInINR: 449,
      priceYearlyInUSD: 6.5,
      priceTwoYearlyInUSD: 6.3,
      priceThreeYearlyInUSD: 5.9,
      priceYearlyInEUR: 6.2,
      priceTwoYearlyInEUR: 6,
      priceThreeYearlyInEUR: 5,
      // Save the price data
      priceYearlySaveInINR:  33999,
      priceTwoYearlySaveInINR:  33999,
      priceThreeYearlySaveInINR:  33999,
      priceYearlySaveInUSD:399,
      priceTwoYearlySaveInUSD: 399,
      priceThreeYearlySaveInUSD: 399,
      priceYearlySaveInEUR: 369,
      priceTwoYearlySaveInEUR: 369,
      priceThreeYearlySaveInEUR: 369,
    },
    {
      id: 2,
      name: "POPO XXL",
      priceYearlyInINR: 599,
      priceTwoYearlyInINR: 589,
      priceThreeYearlyInINR: 559,
      priceYearlyInUSD: 7.5,
      priceTwoYearlyInUSD: 7.3,
      priceThreeYearlyInUSD: 6.9,
      priceYearlyInEUR: 7.2,
      priceTwoYearlyInEUR: 7,
      priceThreeYearlyInEUR: 6,
      // Save the price data
      priceYearlySaveInINR:  33999,
      priceTwoYearlySaveInINR:  33999,
      priceThreeYearlySaveInINR:  33999,
      priceYearlySaveInUSD:399,
      priceTwoYearlySaveInUSD: 399,
      priceThreeYearlySaveInUSD: 399,
      priceYearlySaveInEUR: 369,
      priceTwoYearlySaveInEUR: 369,
      priceThreeYearlySaveInEUR: 369,
    },
   
  ],
  linuxData: [
    {
      id: 0,
      name: "RockeyBoost",
      priceYearlyInINR: 120,
      priceTwoYearlyInINR: 140,
      priceThreeYearlyInINR: 160,
      priceYearlyInUSD: 13,
      priceTwoYearlyInUSD: 14,
      priceThreeYearlyInUSD: 17,
      priceYearlyInEUR: 12,
      priceTwoYearlyInEUR: 13,
      priceThreeYearlyInEUR: 16,
    },
    {
      id: 1,
      name: "RockyPro",
      priceYearlyInINR: 220,
      priceTwoYearlyInINR: 240,
      priceThreeYearlyInINR: 260,
      priceYearlyInUSD: 23,
      priceTwoYearlyInUSD: 24,
      priceThreeYearlyInUSD: 27,
      priceYearlyInEUR: 22,
      priceTwoYearlyInEUR: 23,
      priceThreeYearlyInEUR: 26,
    },
    {
      id: 2,
      name: "RockyBusiness",
      priceYearlyInINR: 320,
      priceTwoYearlyInINR: 340,
      priceThreeYearlyInINR: 360,
      priceYearlyInUSD: 33,
      priceTwoYearlyInUSD: 34,
      priceThreeYearlyInUSD: 37,
      priceYearlyInEUR: 32,
      priceTwoYearlyInEUR: 33,
      priceThreeYearlyInEUR: 36,
    },
   
  ],
  woocomeData: [
    {
      id: 0,
      name: "Popo Store Easy",
      priceYearlyInINR: 490,
      priceTwoYearlyInINR: 470,
      priceThreeYearlyInINR: 450,
      priceYearlyInUSD: 5.9,
      priceTwoYearlyInUSD: 5.7,
      priceThreeYearlyInUSD: 5.5,
      priceYearlyInEUR: 4.9,
      priceTwoYearlyInEUR: 4.8,
      priceThreeYearlyInEUR: 4.7,
      // Save the price data
      priceYearlySaveInINR:  33999,
      priceTwoYearlySaveInINR:  33999,
      priceThreeYearlySaveInINR:  33999,
      priceYearlySaveInUSD:399,
      priceTwoYearlySaveInUSD: 399,
      priceThreeYearlySaveInUSD: 399,
      priceYearlySaveInEUR: 369,
      priceTwoYearlySaveInEUR: 369,
      priceThreeYearlySaveInEUR: 369,
    },
    {
      id: 1,
      name: "Popo Store Pro",
      priceYearlyInINR: 590,
      priceTwoYearlyInINR: 550,
      priceThreeYearlyInINR: 449,
      priceYearlyInUSD: 6.9,
      priceTwoYearlyInUSD: 6.4,
      priceThreeYearlyInUSD: 6.2,
      priceYearlyInEUR: 5.9,
      priceTwoYearlyInEUR: 5.6,
      priceThreeYearlyInEUR: 5.2,
      // Save the price data
      priceYearlySaveInINR:  33999,
      priceTwoYearlySaveInINR:  33999,
      priceThreeYearlySaveInINR:  33999,
      priceYearlySaveInUSD:399,
      priceTwoYearlySaveInUSD: 399,
      priceThreeYearlySaveInUSD: 399,
      priceYearlySaveInEUR: 369,
      priceTwoYearlySaveInEUR: 369,
      priceThreeYearlySaveInEUR: 369,
    },
    {
      id: 2,
      name: "Popo Store Master",
      priceYearlyInINR: 690,
      priceTwoYearlyInINR: 650,
      priceThreeYearlyInINR: 620,
      priceYearlyInUSD: 7.9,
      priceTwoYearlyInUSD: 7.4,
      priceThreeYearlyInUSD: 7.2,
      priceYearlyInEUR: 6.9,
      priceTwoYearlyInEUR: 6.6,
      priceThreeYearlyInEUR: 6.2,
      // Save the price data
      priceYearlySaveInINR:  33999,
      priceTwoYearlySaveInINR:  33999,
      priceThreeYearlySaveInINR:  33999,
      priceYearlySaveInUSD:399,
      priceTwoYearlySaveInUSD: 399,
      priceThreeYearlySaveInUSD: 399,
      priceYearlySaveInEUR: 369,
      priceTwoYearlySaveInEUR: 369,
      priceThreeYearlySaveInEUR: 369,
    },
   
  ],
};

export default products;
