const RightData = [
    {   
        id : 21,
        planTitle : ' Starter plan',
        planPiceF : '19',
        planPicePaisa : '.99',
        planCurrency : '$',
        planOffer : 'Save 40%',
        planIcon : <i className="feather icon-check"></i>,
        planList1 : 'Commercial License',
        planList2 : '00+ HTML UI Elements',
        planList3 : 'Unlimited Domain Support', 
        planList4 : '6 months premium support',
        planList15 : 'Lifetime updates',
        bgColor: "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(85,74,237,1) 70%)",
        smallTitleColor: "#fff",
        planbadgeBgColor: "#ecebfd",
        planbadgeTextColor: "#000",
     },
     {  
        
         id : 22,
         planTitle : ' Starter plan',
        planPiceF : '20',
        planPicePaisa : '.99',
        planCurrency : '$',
        planOffer : 'Save 40%',
        planIcon : <i className="feather icon-check"></i>,
        planList1 : 'Commercial License',
        planList2 : '00+ HTML UI Elements',
        planList3 : 'Unlimited Domain Support',
        planList4 : '6 months premium support',
        planList5 : 'Lifetime updates',
        bgColor: "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(74,201,237,1) 70%)"
     },
     {  
         id : 23,
         planTitle : ' Starter plan',
         planPiceF : '21',
         planPicePaisa : '.99',
         planCurrency : '$',
         planOffer : 'Save 40%',
         planIcon : <i className="feather icon-check"></i>,
         planList1 : 'Commercial License',
         planList2 : '00+ HTML UI Elements',
         planList3 : 'Unlimited Domain Support',
         planList4 : '6 months premium support',
         planList5 : 'Lifetime updates',
         bgColor: "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(74,237,180,1) 70%)"
     },
     {  
         id : 24,
         planTitle : ' Starter plan',
         planPiceF : '22',
         planPicePaisa : '.99',
         planCurrency : '$',
         planOffer : 'Save 40%',
         planIcon : <i className="feather icon-check"></i>,
         planList1 : 'Commercial License',
         planList2 : '00+ HTML UI Elements',
         planList3 : 'Unlimited Domain Support',
         planList4 : '6 months premium support',
         planList5 : 'Lifetime updates',
         bgColor: "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(237,213,74,1) 70%)"
     },
]

export default RightData;