const RightData = [
    {   
        id : 21,
        planTitle : 'WooCommerce Hosting', 
        planPiceF : '449',
        planPicePaisa : '/ month',
        planCurrency : '₹',
        planOffer : 'Save 40%',
        planIcon : <i className="feather icon-check"></i>,
        planList1 : 'WordPress Hosting        ',
        planList2 : '20 GB Web Space        ',
        planList3 : 'Unmetered Traffic        ', 
        planList4 : 'Free SSL & Enhanced Security',
        planList5 : 'Managed WordPress        ',
        bgColor: "linear-gradient(162deg, rgba(9,187,254,1) 13%, rgba(86,72,237,1) 66%)",
        smallTitleColor: "#fff",
        planbadgeBgColor: "#ecebfd",
        planbadgeTextColor: "#000",
        billedCat: "Triannually",
     },
     {  

         id : 22,
         planTitle : ' Professional Business Email',
        planPiceF : '125',
        planPicePaisa : '/ month',
        planCurrency : '₹',
        planOffer : 'Save 40%',
        planIcon : <i className="feather icon-check"></i>,
        planList1 : 'Commercial License',
        planList2 : '30GB Storage        ',
        planList3 : 'Never miss a meeting        ',
        planList4 : 'Communicate on the go        ',
        planList5 : 'Intelligent Collaboration        ',
        bgColor: "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(74,201,237,1) 70%)",
        billedCat: "Triannually",
     },
     {  
         id : 23,
         planTitle : 'Premium SSL Certificate',
         planPiceF : '02',
         planPicePaisa : '.5 / month',
         planCurrency : '₹',
         planOffer : 'Save 40%',
         planIcon : <i className="feather icon-check"></i>,
         planList1 : 'Commercial License',
         planList2 : 'Domain Validation         ',
         planList3 : 'Solid Security',
         planList4 : 'Increase SEO Ranking',
         planList5 : '$10,000 warranty level         ',
         bgColor: "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(74,237,180,1) 70%)",
         billedCat: "Triannually",
     },
     {  
         id : 24,
         planTitle : '250GB/ Object Storage         ',
         planPiceF : '325',
         planPicePaisa : '/ month',
         planCurrency : '₹',
         planOffer : 'Save 40%',
         planIcon : <i className="feather icon-check"></i>,
         planList1 : 'Commercial License',
         planList2 : 'S3-Compatible API         ',
         planList3 : 'Always-On DDos Protection         ',
         planList4 : 'Guaranteed Redundancy         ',
         planList5 : 'Works Well with Any Serve',
         bgColor: "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(237,213,74,1) 70%)",
         billedCat: "Monthly",
     },
]

export default RightData;